// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportFirst.Data;

#nullable disable

namespace SportFirst.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250123205807_initMigration")]
    partial class initMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportFirst.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReservationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SelectedSport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "henso@gmail.com",
                            Name = "Max",
                            ReservationDateTime = new DateTime(2024, 12, 29, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            SelectedSport = "Tennis",
                            Surname = "Hensonn"
                        },
                        new
                        {
                            Id = 2,
                            Email = "yeats@gmail.com",
                            Name = "Tom",
                            ReservationDateTime = new DateTime(2024, 12, 29, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            SelectedSport = "Squash",
                            Surname = "Yeat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
